#define KEYBOARDCONTROL		1
#define MOUSECONTROL		2
#define CONTROLMESSAGE		3


#define	MOUSEMOVE			0
#define MOUSELEFT			1
#define MOUSERIGHT			2
#define MOUSEDOUBLECLICK	3
#define MOUSESINGLECLICK	4


#define CNTRL_RESOLUTION	1
